-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:

-- Exercise 1: Count the number of trips in January 2023

SELECT data_file_month AS MONTH,COUNT(vendor_id) AS Number_of_Rides
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE data_file_month = 1
GROUP BY data_file_month;

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023

SELECT SUM(fare_amount) AS TOTAL_REVENUE
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 3: Find the most popular pickup location

SELECT pickup_location_id, COUNT(pickup_location_id) AS NUMBER_OF_PICKUPS
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY pickup_location_id
ORDER BY NUMBER_OF_PICKUPS DESC
LIMIT 1;

-- Exercise 4: Analyze the number of trips per hour of the day

SELECT EXTRACT(HOUR FROM pickup_datetime) AS Hour_of_Day,COUNT(*) AS Number_of_Trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY Hour_of_Day
ORDER BY Number_of_Trips DESC;

-- Exercise 5: Calculate the average trip distance

SELECT ROUND(AVG(trip_distance), 2)
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 6: Find the longest trip by distance

SELECT ROUND((trip_distance), 2)
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
ORDER BY ROUND((trip_distance), 2) DESC
LIMIT 1;

-- OR

SELECT ROUND(MAX(trip_distance), 2) AS Max_Trip_Distance
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 7: Calculate the total number of passengers by payment type

SELECT payment_type, SUM(passenger_count) NUMBER_OF_PASSENGERS
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY payment_type;

-- Exercise 8: Find the most common drop-off location for trips paid by payment type 1

SELECT dropoff_location_id, COUNT(*) AS Number_of_Trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE payment_type = '1'
GROUP BY dropoff_location_id
ORDER BY Number_of_Trips DESC
LIMIT 1; 

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers

SELECT COUNT(*) AS Number_of_Trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE passenger_count > 4;

-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance

SELECT AVG(fare_amount)
FROM (SELECT * 
      FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
      WHERE trip_distance > (SELECT ROUND(AVG(trip_distance), 2)
                              FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022));